# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Copious Notes
author: Mark Townsend
email: mark@markltownsend.com
# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: "A place where I write about programming topics I'm learning about.  Mostly iOS, perhaps some Android."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.markltownsend.com" # the base hostname & protocol for your site, e.g. http://example.com
url-pretty: "markltownsend.com"

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/images/Profile_2021.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

post_search: true

# The keywords to associate with your website, for SEO purposes
keywords: "developer,software engineer,swift language,swift,objective-c,ios,apple,macos"

# navbar-links:
#   About: "about"

social-network-links:
  email: mark@markltownsend.com
  linkedin: markltownsend
  github: markltownsend
  mastodon: iosdev.space/@markltownsend

remove-ads: true

#################################
# --- Web Analytics Section --- #
#################################

# Fill in your Google Analytics tag ID (or "Measurement ID") to track your website usage
gtag: G-FD4ZQGLYPS

# Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

######################################
# --- Colors / background image --- #
######################################

# Personalize the colors in your website. Color values can be any valid CSS color

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of color

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a color for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# Build settings
# theme: minima
remote_theme: daattali/beautiful-jekyll@6.0.1



permalink: /:year-:month-:day-:title/
paginate: 5
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-feed
  - jekyll-compose
  - jekyll-timeago
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap