# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Copious Notes
author: Mark Townsend
email: mark@markltownsend.com
description: >- # this means to ignore newlines until "baseurl:"
  A place where I write about programming topics I'm learning about.  Mostly iOS, perhaps some Android.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.markltownsend.com" # the base hostname & protocol for your site, e.g. http://example.com
url-pretty: "markltownsend.com"

post_search: true

# navbar-links:
#   About: "about"

social-network-links:
  email: mark@markltownsend.com
  linkedin: markltownsend
  github: markltownsend
  mastodon: iosdev.space/@markltownsend

remove-ads: true

# Build settings
# theme: minima
remote_theme: daattali/beautiful-jekyll@6.0.1

plugins:
  - jekyll-feed
  - jekyll-compose
  - jekyll-timeago
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

# Google Analytics
gtag: G-FD4ZQGLYPS

exclude:
  - CNAME